CREATE TABLE IF NOT EXISTS users (
id integer PRIMARY KEY AUTOINCREMENT,
email text NOT NULL,
psw text NOT NULL,
image BLOB DEFAULT NULL,
styleID integer DEFAULT 1,
confirmed_mail BIT DEFAULT 0,
time integer DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS styles (
id INTEGER DEFAULT NULL,
styleImage BLOB DEFAULT NULL
);